name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Special build for GitHub Pages
      - name: Prepare static files
        run: |
          mkdir -p dist
          cp -f attached_assets/UmeshmResume.pdf client/public/ || echo "Resume file not found, skipping"
          
          # Copy static component files to main components
          cp -f client/src/components/ContactSection.static.tsx client/src/components/ContactSection.tsx || echo "Static file not found, skipping"
          cp -f client/src/App.static.tsx client/src/App.tsx || echo "Static file not found, skipping"
          cp -f client/src/main.static.tsx client/src/main.tsx || echo "Static file not found, skipping"
      
      # Build the project
      - name: Build
        run: |
          # Set base for GitHub Pages
          echo '{ "base": "./" }' > vite.config.json
          npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
